# permissions for end users to edit proxyassemblages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: proxyassemblage-editor-role
rules:
- apiGroups:
  - fleet.squaremo.dev
  resources:
  - proxyassemblages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fleet.squaremo.dev
  resources:
  - proxyassemblages/status
  verbs:
  - get
